# encoding=utf-8
DEBUG = False
ADDRESS = ('127.0.0.1', 5037)
CVSTRATEGY_ANDROID = ["siftpre", "siftnopre", "tpl"]
CVSTRATEGY_WINDOWS = ["tpl", "siftnopre"]
MASK_RECT = None # 非全屏运行时，屏蔽掉的区域
THRESHOLD = 0.6
THRESHOLD_STRICT = 0.7
PLAYRES = []
CVINTERVAL = 0.5
OPDELAY = 0.1
TIMEOUT = 20
LOGFILE = "log.txt"
SCREEN_DIR = "img_record"
REFRESH_SCREEN_DELAY = 5 # 设备发生屏幕旋转时，需要等待5s左右才能确定旋转完毕(大部分设备)
RECONNECT_TIMES = 5
RESIZE_METHOD = None
SCRIPTHOME = None
SRC_RESOLUTION = []
